stages:
  - prometheus_check
  - deploy


prometheus_check:
  image: alpine:3.1Û´
  stage: prometheus_check
  except:
    - master
  script:
    - mkdir -p /usr/local/sbin/
    - wget https://github.com/prometheus/prometheus/releases/download/v2.51.0-rc.0/prometheus-2.51.0-rc.0.linux-amd64.tar.gz -P /usr/local/sbin
    - tar xvfz prometheus-*.tar.gz
    - chmod +x /usr/local/sbin/promtool
    - /usr/local/sbin/promtool check config prometheus.yml

.deploy-cloud: &deploy_cloud
  image: openshift/origin-cli:v4.0.0
  stage: deploy
  only:
    - master
  before_script:
    - oc version  
    - oc login https://api.okd4.${REGION}. YOUR_URL .io:YOUR_PORT --token=${PRODUCTION_TOKEN}
    - oc project ${OKD_PROJECT} >>> #variable
    - oc create configmap prometheus-conf --from-file=prometheus.yml -o yaml --dry-run | oc replace -f -
    - oc create configmap prometheus-rules --from-file=rules/ -o yaml --dry-run | oc replace -f -
    - oc create configmap prometheus-file-sd --from-file=file_sd/ -o yaml --dry-run | oc replace -f -
    - oc apply -f statefulset.yml
  script:
    - sleep 15
    - curl -XPOST YOUR_ROUTE/-/reload
  <<: *deploy_cloud
